apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - name: pipeline
        image: southamerica-east1-docker.pkg.dev/vivae-mgt-358520/teste-cloud-build/pipeline:779f839
        ports:
          - containerPort: 8080
